---
title: "Example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tabm)
# 5 nested list: General options, headercss, headerevents, General css columns, Single css columns
list_opts = list(
  #general options
  general_list = list(language="ES"), #EN and ES
  #header css
  table_list_css_header=list("'color'"="'black'","'background-color'"="'yellow'"), #color,back,
  #header events
  list2= list(),
  #colnames style #single pararameter for all
  table_list_css_column= list(columns=c(1,2,3,4,5), fontWeight="normal", color = "gray", backgroundColor = "green"),
  table_list_css_column_single = list(
                            list(columns=c(1),  fontWeight="normal", color = "yellow", backgroundColor = "green"),
                            list(columns=c(2),  fontWeight="normal", color = "black", backgroundColor = "green"))

)

runtable(iris,list_opts)

```
